In [1]:
import pandas as pd

In [4]:
food = pd.read_csv('food.csv')

In [5]:
food

              Name Gender       City Frequency             Item  Spends
0           Nitish      M    kolkata    weekly           burger      11
1              anu      F    gurgaon     daily         sandwich      14
2            mukku      M    kolkata      once             vada      25
3             suri      M    kolkata   monthly            pizza      56
4            rajiv      M      patna     never           panner      34
5          barjraj      M      Delhi    weekly           Samosa      57
6           ramdin      F    Kolkata     daily       Manchurian     138
7           sharat      M     Mumbai      once    Chole Bhature     135
8         birender      F  Hyderabad     never        Pani Puri     179
9             amit      F  Bengaluru     never           Pakora     181
10          kushal      M    Chennai    weekly     French Fries      87
11           kasid      F  Ahmedabad     never            Rolls     154
12            shiv      M      Surat      once            Patty     124
13          vikram      F       Pune   monthly    Cheese Burger     109
14          sanjay      F     Jaipur     never            Pasta      35
15            abhi      M     Kanpur     never    Chicken Tikka     155
16             ram      M    Lucknow     daily            Pizza      49
17          khadak      F     Nagpur    weekly          Noodles     146
18          gurmit      M  Ghaziabad   monthly         Sandwich      67
19      chanderpal      M     Indore     never         Bhelpuri      66
20            aman      M      Delhi    weekly  Dahi Papdi Chat      33
21         khursid      M    Kolkata     daily        Pani Puri     120
22           rohit      M     Mumbai     never            pizza     106
23        mohabbat      M  Hyderabad   monthly     French Fries     182
24       raj kumar      M  Bengaluru     never        Pani Puri     127
25         jaswant      F    Chennai    weekly           panner      87
26           sevak      M  Ahmedabad     never         Sandwich     138
27        chotelal      M      Surat      once            Pasta      85
28            amit      F       Pune   monthly            Rolls     162
29          rupesh      M     Jaipur     never        Pani Puri     122
30           midda      F     Kanpur    weekly  Dahi Papdi Chat     174
31    dharam Singh      M    Lucknow     never          Noodles     187
32     manoj yadav      M     Nagpur      once            Patty     156
33       ram Singh      F  Ghaziabad     daily        Pani Puri      65
34   preetam kumar      M     Indore     never        Pani Puri      23
35       ram kumar      M      Delhi    weekly        Pani Puri      64
36          saraln      F    Kolkata     daily  Dahi Papdi Chat      99
37    pankaj kumar      M     Mumbai      once     French Fries      75
38    sheak shakir      M  Hyderabad     daily            Pizza     113
39     riyasat ali      F  Bengaluru     never           panner     136
40  Vinit katariya      M    Chennai    weekly     French Fries     180
41           sumit      F  Ahmedabad     daily         Bhelpuri     128
42         arindra      M      Surat      once          Noodles      86

In [8]:
food.pivot_table(index=['City','Gender'],columns='Item',values='Spends',aggfunc='mean')

Item              Bhelpuri  Cheese Burger  Chicken Tikka  Chole Bhature  \
City      Gender
Ahmedabad F          128.0            NaN            NaN            NaN
          M            NaN            NaN            NaN            NaN
Bengaluru F            NaN            NaN            NaN            NaN
          M            NaN            NaN            NaN            NaN
Chennai   F            NaN            NaN            NaN            NaN
          M            NaN            NaN            NaN            NaN
Delhi     M            NaN            NaN            NaN            NaN
Ghaziabad F            NaN            NaN            NaN            NaN
          M            NaN            NaN            NaN            NaN
Hyderabad F            NaN            NaN            NaN            NaN
          M            NaN            NaN            NaN            NaN
Indore    M           66.0            NaN            NaN            NaN
Jaipur    F            NaN            NaN            NaN            NaN
          M            NaN            NaN            NaN            NaN
Kanpur    F            NaN            NaN            NaN            NaN
          M            NaN            NaN          155.0            NaN
Kolkata   F            NaN            NaN            NaN            NaN
          M            NaN            NaN            NaN            NaN
Lucknow   M            NaN            NaN            NaN            NaN
Mumbai    M            NaN            NaN            NaN          135.0
Nagpur    F            NaN            NaN            NaN            NaN
          M            NaN            NaN            NaN            NaN
Pune      F            NaN          109.0            NaN            NaN
Surat     M            NaN            NaN            NaN            NaN
gurgaon   F            NaN            NaN            NaN            NaN
kolkata   M            NaN            NaN            NaN            NaN
patna     M            NaN            NaN            NaN            NaN

Item              Dahi Papdi Chat  French Fries  Manchurian  Noodles  Pakora  \
City      Gender
Ahmedabad F                   NaN           NaN         NaN      NaN     NaN
          M                   NaN           NaN         NaN      NaN     NaN
Bengaluru F                   NaN           NaN         NaN      NaN   181.0
          M                   NaN           NaN         NaN      NaN     NaN
Chennai   F                   NaN           NaN         NaN      NaN     NaN
          M                   NaN         267.0         NaN      NaN     NaN
Delhi     M                  33.0           NaN         NaN      NaN     NaN
Ghaziabad F                   NaN           NaN         NaN      NaN     NaN
          M                   NaN           NaN         NaN      NaN     NaN
Hyderabad F                   NaN           NaN         NaN      NaN     NaN
          M                   NaN         182.0         NaN      NaN     NaN
Indore    M                   NaN           NaN         NaN      NaN     NaN
Jaipur    F                   NaN           NaN         NaN      NaN     NaN
          M                   NaN           NaN         NaN      NaN     NaN
Kanpur    F                 174.0           NaN         NaN      NaN     NaN
          M                   NaN           NaN         NaN      NaN     NaN
Kolkata   F                  99.0           NaN       138.0      NaN     NaN
          M                   NaN           NaN         NaN      NaN     NaN
Lucknow   M                   NaN           NaN         NaN    187.0     NaN
Mumbai    M                   NaN          75.0         NaN      NaN     NaN
Nagpur    F                   NaN           NaN         NaN    146.0     NaN
          M                   NaN           NaN         NaN      NaN     NaN
Pune      F                   NaN           NaN         NaN      NaN     NaN
Surat     M                   NaN           NaN         NaN     86.0     NaN
gurgaon   F                   NaN           NaN         NaN      NaN     NaN
kolkata   M                   NaN           NaN         NaN      NaN     NaN
patna     M                   NaN           NaN         NaN      NaN     NaN

Item              Pani Puri  ...  Patty  Pizza  Rolls  Samosa  Sandwich  \
City      Gender             ...
Ahmedabad F             NaN  ...    NaN    NaN  154.0     NaN       NaN
          M             NaN  ...    NaN    NaN    NaN     NaN     138.0
Bengaluru F             NaN  ...    NaN    NaN    NaN     NaN       NaN
          M           127.0  ...    NaN    NaN    NaN     NaN       NaN
Chennai   F             NaN  ...    NaN    NaN    NaN     NaN       NaN
          M             NaN  ...    NaN    NaN    NaN     NaN       NaN
Delhi     M            64.0  ...    NaN    NaN    NaN    57.0       NaN
Ghaziabad F            65.0  ...    NaN    NaN    NaN     NaN       NaN
          M             NaN  ...    NaN    NaN    NaN     NaN      67.0
Hyderabad F           179.0  ...    NaN    NaN    NaN     NaN       NaN
          M             NaN  ...    NaN  113.0    NaN     NaN       NaN
Indore    M            23.0  ...    NaN    NaN    NaN     NaN       NaN
Jaipur    F             NaN  ...    NaN    NaN    NaN     NaN       NaN
          M           122.0  ...    NaN    NaN    NaN     NaN       NaN
Kanpur    F             NaN  ...    NaN    NaN    NaN     NaN       NaN
          M             NaN  ...    NaN    NaN    NaN     NaN       NaN
Kolkata   F             NaN  ...    NaN    NaN    NaN     NaN       NaN
          M           120.0  ...    NaN    NaN    NaN     NaN       NaN
Lucknow   M             NaN  ...    NaN   49.0    NaN     NaN       NaN
Mumbai    M             NaN  ...    NaN    NaN    NaN     NaN       NaN
Nagpur    F             NaN  ...    NaN    NaN    NaN     NaN       NaN
          M             NaN  ...  156.0    NaN    NaN     NaN       NaN
Pune      F             NaN  ...    NaN    NaN  162.0     NaN       NaN
Surat     M             NaN  ...  124.0    NaN    NaN     NaN       NaN
gurgaon   F             NaN  ...    NaN    NaN    NaN     NaN       NaN
kolkata   M             NaN  ...    NaN    NaN    NaN     NaN       NaN
patna     M             NaN  ...    NaN    NaN    NaN     NaN       NaN

Item              burger  panner  pizza  sandwich  vada
City      Gender
Ahmedabad F          NaN     NaN    NaN       NaN   NaN
          M          NaN     NaN    NaN       NaN   NaN
Bengaluru F          NaN   136.0    NaN       NaN   NaN
          M          NaN     NaN    NaN       NaN   NaN
Chennai   F          NaN    87.0    NaN       NaN   NaN
          M          NaN     NaN    NaN       NaN   NaN
Delhi     M          NaN     NaN    NaN       NaN   NaN
Ghaziabad F          NaN     NaN    NaN       NaN   NaN
          M          NaN     NaN    NaN       NaN   NaN
Hyderabad F          NaN     NaN    NaN       NaN   NaN
          M          NaN     NaN    NaN       NaN   NaN
Indore    M          NaN     NaN    NaN       NaN   NaN
Jaipur    F          NaN     NaN    NaN       NaN   NaN
          M          NaN     NaN    NaN       NaN   NaN
Kanpur    F          NaN     NaN    NaN       NaN   NaN
          M          NaN     NaN    NaN       NaN   NaN
Kolkata   F          NaN     NaN    NaN       NaN   NaN
          M          NaN     NaN    NaN       NaN   NaN
Lucknow   M          NaN     NaN    NaN       NaN   NaN
Mumbai    M          NaN     NaN  106.0       NaN   NaN
Nagpur    F          NaN     NaN    NaN       NaN   NaN
          M          NaN     NaN    NaN       NaN   NaN
Pune      F          NaN     NaN    NaN       NaN   NaN
Surat     M          NaN     NaN    NaN       NaN   NaN
gurgaon   F          NaN     NaN    NaN      14.0   NaN
kolkata   M         11.0     NaN   56.0       NaN  25.0
patna     M          NaN    34.0    NaN       NaN   NaN

[27 rows x 21 columns]